version: "3"
services:
  fvlrws:
    image: fvlrws
    ports:
      - 9091:9091
    networks:
      - vlr_network
    environment:
      - PORT=9092
      - PB_URI="http://localhost:8090"
      - PB_USERNAME="ws@fantasyvlr.xyz"
      - PB_PASSWORD="testtesttest"

networks:
  vlr_network:
