FROM node:latest
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

EXPOSE 9092

# Start the app
CMD ["npm", "start"]
# Add your Dockerfile instructions here
